DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS answer;

CREATE TABLE player (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uname VARCHAR(16) UNIQUE NOT NULL,
    roomCode CHAR(4) NOT NULL
);

CREATE TABLE question (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    body TEXT NOT NULL
);

CREATE TABLE answer (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    body TEXT NOT NULL,
    player_id INTEGER NOT NULL,
    FOREIGN KEY (player_id) REFERENCES player (id)
);